apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-info-service-ext
  namespace: ossm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: host-info-service-ext
  template:
    metadata:
      labels:
        app: host-info-service-ext
    spec:
      containers:
        - name: host-info-service-ext
          image: yzgang1976/host-info-service:latest
          ports:
            - containerPort: 8082
              protocol: TCP
